import mongoose from "mongoose";

const taskSchema = new mongoose.Schema(
	{
		title: {
			type: String,
			required: true,
		},

		description: String,

		type: {
			type: String,
			enum: ["call", "whatsapp", "meeting", "visit", "demo", "followup", "payment"],
			required: true,
		},

		status: {
			type: String,
			enum: ["pending", "completed", "overdue", "cancelled"],
			default: "pending",
		},

		priority: {
			type: String,
			enum: ["low", "medium", "high"],
			default: "medium",
		},

		dueDate: {
			type: Date,
			required: true,
		},

		completedAt: Date,

		// Relations
		assignedTo: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "User",
			required: true,
		},

		assignedBy: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "User",
		},

		lead: {
			type: mongoose.Schema.Types.ObjectId,
			ref: "Lead",
		},
   

		// Extra CRM fields
		lastRemark: String,
		nextAction: String,

		isAutoGenerated: {
			type: Boolean,
			default: false,
		},
	},
	{ timestamps: true },
);

const Task = mongoose.models.Task || mongoose.model("Task", taskSchema);

export default Task;
